(function(root,factory){
  if(typeof module==='object'&&module.exports){
    module.exports=factory(require('./sports.js'));
  }else{
    root.TEAM_APP_SPORTS=factory(root.TEAM_APP_SPORTS||{});
  }
})(typeof globalThis!=='undefined'?globalThis:this,function(sourceRegistry){
  'use strict';

  // sports.js validates and freezes its adapters. Build a new top-level registry so
  // reviewed coaching content can be layered on without weakening immutability.
  const registry=Object.fromEntries(Object.entries(sourceRegistry||{}).map(([key,sport])=>[key,{...sport}]));

  const lesson=(title,where,responsibilities,skills,tip)=>({title,where,responsibilities,skills,tip});
  const drill=(id,title,minutes,category,focus,equipment,steps)=>({id,title,minutes,category,focus,equipment,steps});

  function fillLessons(sportKey,guides,overrides={}){
    const sport=registry[sportKey];if(!sport)return;
    const out={...(sport.lessons||{})};
    for(const pos of sport.allPositions||sport.positions||[]){
      if(out[pos.code])continue;
      const custom=overrides[pos.code];if(custom){out[pos.code]=custom;continue;}
      const guide=guides[pos.group]||guides.default;
      out[pos.code]=lesson(pos.name,guide.where(pos),guide.responsibilities(pos),guide.skills(pos),guide.tip(pos));
    }
    sport.lessons=out;
  }
  function addLibrary(sportKey,drills,map){const sport=registry[sportKey];if(!sport)return;sport.drills=drills;sport.skillDrillMap=map;sport.contentStatus='reviewed-fundamentals';}

  const diamondGuides={
    infield:{
      where:p=>`${p.name} works on the infield and adjusts depth to the hitter, runners and game situation.`,
      responsibilities:p=>['Get ready before every pitch and know the next likely play.','Field or receive the ball under control, then make the simplest available out.','Cover assigned bases and communicate loudly with nearby teammates.'],
      skills:p=>['Ready position and first step','Catching and throwing accuracy','Footwork around bases','Situational awareness'],
      tip:p=>'Move your feet first, keep your eyes on the ball, and make one clear decision at a time.'
    },
    outfield:{
      where:p=>`${p.name} covers an outfield zone behind the infield and backs up throws and neighboring fielders.`,
      responsibilities:p=>['Read the ball immediately off the bat and move to get behind it when possible.','Call fly balls loudly and avoid collisions.','Throw through the appropriate cutoff and back up bases when the play moves elsewhere.'],
      skills:p=>['Fly-ball tracking','Ground-ball approach','Crow-hop throwing','Communication and backup responsibilities'],
      tip:p=>'Assume every ball can involve you—move on contact even when it is hit to another part of the field.'
    },
    default:{where:p=>`${p.name} supports the team from a defined defensive role.`,responsibilities:p=>['Be ready before each pitch.','Communicate and support the next play.'],skills:p=>['Position awareness','Ball skills'],tip:p=>'Know where the ball and next play are before every pitch.'}
  };
  fillLessons('softball',diamondGuides,{
    P:lesson('Pitcher','In the pitching circle, beginning each defensive play.',['Deliver legal pitches using the mechanics required by the selected rule set.','Finish in a balanced fielding position and react to bunts or balls near the circle.','Communicate coverage and backup responsibilities with the catcher and infield.'],['Repeatable underhand mechanics','Command and change of speed','Fielding after the pitch','Composure'],'Prioritize balance and repeatable motion before adding speed or movement.'),
    C:lesson('Catcher','Behind home plate, facing the field and organizing the defense.',['Receive pitches safely and keep blocked balls in front.','Communicate outs, runners and defensive priorities.','Field short balls and protect home plate according to the selected rules.'],['Receiving','Blocking','Throwing footwork','Leadership communication'],'Stay balanced and keep the ball in front before worrying about a quick throw.')
  });
  addLibrary('softball',[
    drill('sb-ready-grounders','Ready Position Grounders',12,'Defense','First step, fielding out front and moving through the throw.','Softballs, cones',['Use short lines so every player gets frequent reps.','Roll or hit controlled grounders from different angles.','Cue feet to the ball, glove out front and finish toward the target.']),
    drill('sb-throw-targets','Throwing Target Ladder',10,'Throwing','Accurate throws with controlled distance progression.','Softballs',['Pair players close enough for easy accurate throws.','Move back only after several clean chest-high catches.','Finish with game-speed catch-and-throw footwork.']),
    drill('sb-circle-fielding','Pitcher Circle Fielding',12,'Defense','Pitcher reaction, bunt reads and safe throws to first.','Softballs, cones',['Start with slow rollers around the circle.','Pitcher finishes balanced, fields with two hands when practical and sets feet.','Progress to coach-called first-base or lead-base decisions.']),
    drill('sb-tee-zones','Tee Contact Zones',12,'Hitting','Balanced contact at several strike-zone locations.','Tee, softballs, net',['Begin middle-middle and establish balance.','Move the tee in/out and up/down one location at a time.','Keep the same controlled finish and line-drive intent.']),
    drill('sb-front-toss','Short Front Toss',12,'Hitting','Timing and compact contact against a consistent toss.','Softballs, screen/net',['Use a protected toss position.','Keep toss speed and location predictable at first.','Rotate quickly and reward hard contact through the middle.']),
    drill('sb-baserun-reads','Base Running Reads',12,'Running','Running through, rounding and reacting to coach cues.','Bases, cones',['Rehearse running through first on an infield play.','Rehearse a controlled round on a ball through the infield.','Add hold/go/return cues after players show safe turns.']),
    drill('sb-relay-chain','Outfield Relay Chain',15,'Team','Cutoff alignment, loud communication and quick transfers.','Softballs, bases',['Place an outfielder, cutoff and target base.','Walk through alignment before adding throws.','Rotate everyone through each role and reward accurate one-hop or chest-high throws.']),
    drill('sb-situations','Situation Walkthrough',15,'Team','Pre-pitch decisions with runners and outs.','Field, softballs',['Set runners and announce outs.','Ask defenders to state their first responsibility.','Put a controlled ball in play and briefly review the decision before the next rep.'])
  ],{throwing:['sb-throw-targets','sb-relay-chain'],fielding:['sb-ready-grounders','sb-circle-fielding'],hitting:['sb-tee-zones','sb-front-toss'],baserunning:['sb-baserun-reads'],awareness:['sb-situations','sb-relay-chain']});

  const soccerGuides={
    goalkeeper:{where:p=>'Inside and around the penalty area, organizing the team from the deepest position.',responsibilities:p=>['Protect the goal and choose when to catch, parry or play with the feet.','Communicate early with defenders and support team buildup.','Set position based on the ball, goal and nearby attackers.'],skills:p=>['Set position','Handling','Distribution','Communication'],tip:p=>'Get set before the shot and use a clear voice before the danger arrives.'},
    defense:{where:p=>`${p.name} usually starts in the defensive line and supports both defending and buildup.`,responsibilities:p=>['Protect the space between the ball and goal.','Delay attackers and provide cover for teammates.','Receive and pass under control to help the team play forward.'],skills:p=>['Defensive stance','1v1 delay','Passing under pressure','Cover and communication'],tip:p=>'Stay goal-side, slow the attacker down, and avoid diving in.'},
    midfield:{where:p=>`${p.name} connects the defensive and attacking lines through central or wide midfield spaces.`,responsibilities:p=>['Create passing angles before receiving.','Scan for pressure, teammates and space.','Support both attack and defense as possession changes.'],skills:p=>['First touch','Scanning','Passing','Movement off the ball'],tip:p=>'Check your shoulder before the ball arrives so your first touch has a purpose.'},
    attack:{where:p=>`${p.name} plays high or wide to stretch the defense and create scoring chances.`,responsibilities:p=>['Create separation and useful passing lanes.','Protect the ball or combine quickly when receiving under pressure.','Attack the goal with purposeful runs and finish when the chance is right.'],skills:p=>['First touch','1v1 attacking','Finishing','Timing of runs'],tip:p=>'Move before the pass—good timing creates more space than standing and waiting.'},
    default:{where:p=>`${p.name} supports team shape on the pitch.`,responsibilities:p=>['Create useful space.','Support the ball and defend when possession changes.'],skills:p=>['Ball control','Awareness'],tip:p=>'Scan, move, communicate.'}
  };
  fillLessons('soccer',soccerGuides);
  addLibrary('soccer',[
    drill('sc-ball-box','Ball Mastery Box',10,'Technical','Comfort with both feet while changing direction and speed.','Ball per player, cones',['Create a safe grid with room between players.','Use inside/outside touches and controlled sole turns.','Add head-up scanning cues without turning it into a race.']),
    drill('sc-gates-passing','Passing Through Gates',12,'Technical','Passing weight, receiving shape and movement after the pass.','Balls, cone gates',['Pairs score by passing through a gate to a teammate.','Receiver opens body and takes first touch into space.','After each pass, both players relocate to a new gate.']),
    drill('sc-rondo-4v1','4v1 Keep-Away',12,'Team','Support angles, quick decisions and immediate transition.','Ball, cones',['Set a small grid with four outside players and one defender.','Limit touches only when the group is ready.','On turnover, the player who lost it becomes the defender.']),
    drill('sc-1v1-delay','1v1 Delay Channel',12,'Defense','Staying goal-side, controlling distance and delaying.','Balls, cones',['Create narrow channels with a target line.','Defender starts goal-side and works to slow rather than stab.','Rotate quickly and add recovery support after technique is consistent.']),
    drill('sc-finishing-gates','Finish After First Touch',12,'Attacking','First touch into shooting space and composed finishing.','Balls, goal, cones',['Pass into the attacker from a consistent angle.','First touch must leave the ball playable and away from pressure.','Finish with placement before increasing speed.']),
    drill('sc-overlap-support','Overlap & Support Pattern',12,'Team','Third-player movement and wide support.','Balls, cones',['Walk through pass, support and overlap timing.','Keep players spaced so passing lanes remain clear.','Progress to a passive defender once timing is understood.']),
    drill('sc-transition-3v2','3v2 Transition Game',15,'Game','Fast recognition after winning or losing the ball.','Ball, cones, two mini goals',['Play 3 attackers against 2 defenders in a short field.','On turnover, teams immediately switch attack/defense roles.','Pause only for clear spacing or decision coaching points.']),
    drill('sc-scan-colors','Scan Before Receive',10,'Awareness','Checking shoulders and receiving with information.','Balls, colored cones',['Place colored cones behind receiving players.','Coach calls or shows a color before the pass arrives.','Receiver identifies it, then takes a directional first touch and passes.'])
  ],{ball:['sc-ball-box','sc-scan-colors'],passing:['sc-gates-passing','sc-rondo-4v1'],defending:['sc-1v1-delay','sc-transition-3v2'],finishing:['sc-finishing-gates'],awareness:['sc-scan-colors','sc-transition-3v2'],fitness:['sc-transition-3v2','sc-ball-box']});

  const basketballGuides={
    guard:{where:p=>`${p.name} commonly works on the perimeter, helping organize possessions and protect the ball.`,responsibilities:p=>['Handle pressure and create good passing angles.','Keep floor spacing while recognizing driving and passing lanes.','Sprint back and contain the ball in transition defense.'],skills:p=>['Ball handling','Passing reads','Perimeter shooting','On-ball defense'],tip:p=>'Play with your eyes up—see the defender, teammates and rim before making the next move.'},
    wing:{where:p=>`${p.name} works between the perimeter and lane, cutting, spacing and attacking closeouts.`,responsibilities:p=>['Maintain useful spacing and cut with purpose.','Attack open lanes or move the ball quickly.','Defend perimeter players and help rebound.'],skills:p=>['Triple-threat footwork','Cutting','Finishing','Closeout defense'],tip:p=>'Catch ready to shoot, pass or drive so the defense has to respect all three.'},
    post:{where:p=>`${p.name} operates near the lane, elbows and short corners while also screening and rebounding.`,responsibilities:p=>['Create space with legal screens and strong seals.','Rebound with two hands and protect the ball.','Defend the paint while communicating help responsibilities.'],skills:p=>['Footwork','Screening','Rebounding','Interior finishing'],tip:p=>'Win position before the ball arrives—strong feet make the catch easier.'},
    default:{where:p=>`${p.name} fills a team role on the court.`,responsibilities:p=>['Keep spacing.','Defend and rebound.'],skills:p=>['Footwork','Awareness'],tip:p=>'Move with purpose on both ends.'}
  };
  fillLessons('basketball',basketballGuides);
  addLibrary('basketball',[
    drill('bb-pound-cross','Handle & Change Direction',10,'Technical','Eyes-up control with both hands and simple changes of direction.','Basketball per player, cones',['Start stationary with controlled pound dribbles.','Progress to crossover and retreat dribbles at walking speed.','Finish through a cone lane with eyes up and balanced stops.']),
    drill('bb-pass-cut','Pass-Cut-Fill',12,'Offense','Passing, cutting and replacing open space.','Basketballs, cones',['Set three perimeter spots.','Pass, make a hard basket cut, then fill the open spot.','Add a defender only after spacing and timing are consistent.']),
    drill('bb-form-finish','Form Shooting Ladder',12,'Shooting','Repeatable close-range shooting mechanics and balance.','Basketballs, hoop',['Start close enough to keep mechanics relaxed.','Make several balanced shots before stepping back.','Reset closer if form breaks down.']),
    drill('bb-closeout','Closeout & Contain',12,'Defense','Controlled closeout, balance and keeping the ball in front.','Cones, basketballs',['Defender starts in help position and sprints partway out.','Finish with short choppy steps and hands active.','Offense gets one or two dribbles so defender practices containment.']),
    drill('bb-rebound-outlet','Hit-Find-Rebound-Outlet',12,'Defense','Finding a body, securing the ball and starting transition.','Basketballs, hoop',['Coach shoots or tosses off the rim.','Defender finds an opponent, creates space and pursues the ball.','Secure with two hands, chin the ball and make a strong outlet pass.']),
    drill('bb-advantage-3v2','3v2 Advantage Break',15,'Game','Transition spacing and simple numbers-up decisions.','Basketball, two baskets or half court',['Three attackers begin against two defenders.','Emphasize wide lanes and one decisive pass or finish.','Rotate roles and stop only for major spacing corrections.']),
    drill('bb-drive-kick','Drive & Kick Spacing',12,'Offense','Paint touch, help recognition and relocation.','Basketballs, cones',['Place players at perimeter spots.','Driver attacks a gap while teammates hold or relocate to passing windows.','Finish with catch-and-shoot or one-more-pass decisions.']),
    drill('bb-situation-score','Score/Clock Situations',10,'Awareness','Choosing actions based on score, time and possession.','Basketball, scoreboard/coach calls',['Coach announces a simple score and time scenario.','Players state the priority before play begins.','Run short possessions, then review the decision rather than only the result.'])
  ],{handling:['bb-pound-cross','bb-advantage-3v2'],passing:['bb-pass-cut','bb-drive-kick'],shooting:['bb-form-finish','bb-drive-kick'],defense:['bb-closeout','bb-rebound-outlet'],rebounding:['bb-rebound-outlet'],awareness:['bb-situation-score','bb-advantage-3v2']});

  const footballGuides={
    backfield:{where:p=>`${p.name} aligns in the offensive backfield and works from the snap through the play finish.`,responsibilities:p=>['Know the formation, cadence and assignment before the snap.','Protect the football and execute the designed run, fake, pass or protection responsibility.','Finish each rep under control and reset quickly.'],skills:p=>['Stance and start','Ball security','Footwork','Assignment recognition'],tip:p=>'Alignment and assignment come before speed—be correct first, then be fast.'},
    receiver:{where:p=>`${p.name} aligns on or near the formation edge and creates space in the passing game.`,responsibilities:p=>['Confirm alignment and route responsibility before the snap.','Release under control and run routes at the called depth.','Catch with eyes through the ball and secure it before turning upfield.'],skills:p=>['Stance and release','Route pacing','Catching','Spacing awareness'],tip:p=>'Run every route with a clear landmark instead of drifting toward open grass.'},
    line:{where:p=>`${p.name} works along the line of scrimmage and creates a clean, legal path for the play.`,responsibilities:p=>['Get aligned correctly and identify the blocking responsibility.','Use balanced footwork and legal hand placement taught by the program.','Stay engaged with the play without holding or unsafe contact.'],skills:p=>['Stance','First two steps','Balance','Assignment communication'],tip:p=>'Good blocking starts with feet, leverage and assignment—not reaching.'},
    linebacker:{where:p=>`${p.name} aligns behind the defensive front and connects run fits, coverage and communication.`,responsibilities:p=>['Read the formation and initial backfield action.','Fit the assigned gap or coverage while staying balanced.','Communicate strength, motion and checks with teammates.'],skills:p=>['Read steps','Pursuit angle','Coverage awareness','Communication'],tip:p=>'Take a controlled read step before committing so play fakes do not pull you out of position.'},
    secondary:{where:p=>`${p.name} aligns in the defensive backfield to defend space and eligible receivers.`,responsibilities:p=>['Maintain leverage based on the coverage call.','Track receiver and quarterback cues without losing assignment integrity.','Pursue with safe angles and communicate routes entering or leaving the zone.'],skills:p=>['Backpedal/transition','Leverage','Ball tracking','Communication'],tip:p=>'Protect your leverage first; a disciplined angle is faster than a desperate recovery.'},
    specialist:{where:p=>`${p.name} performs a specialized kicking or snapping role during special teams.`,responsibilities:p=>['Use the same pre-snap routine every rep.','Execute the specialist technique under control.','Communicate readiness and protection timing with the unit.'],skills:p=>['Repeatable setup','Timing','Accuracy','Composure'],tip:p=>'Build consistency with the same setup and rhythm before adding pressure.'},
    returner:{where:p=>`${p.name} aligns deep to receive kicks or punts when allowed by the selected rules.`,responsibilities:p=>['Track the ball first and make the safe catch decision.','Communicate poison/clear/catch decisions as taught by the team.','Secure the ball before accelerating into the return.'],skills:p=>['Ball tracking','Decision making','Ball security','Open-field vision'],tip:p=>'Possession is the first priority; secure the ball before looking for the return lane.'},
    special:{where:p=>`${p.name} fills a coverage or blocking lane on special teams.`,responsibilities:p=>['Know the assigned lane or protection responsibility.','Maintain spacing so teammates can work their lanes.','Use safe, legal technique and play under control through the whistle.'],skills:p=>['Alignment','Lane discipline','Open-field movement','Communication'],tip:p=>'Stay in your lane and keep the play in front of you.'},
    default:{where:p=>`${p.name} has a defined football assignment.`,responsibilities:p=>['Align correctly.','Know the assignment and communicate.'],skills:p=>['Stance','Awareness'],tip:p=>'Assignment before speed.'}
  };
  fillLessons('football',footballGuides,{
    QB:lesson('Quarterback','Behind the center or in shotgun, directing the offense before and after the snap.',['Communicate formation, cadence and any permitted checks.','Secure the snap and carry out the called handoff, fake or pass progression.','Protect possession and make conservative decisions when a play breaks down.'],['Snap exchange','Footwork','Throwing accuracy','Decision making'],'Master the snap and footwork timing before adding complex reads.'),
    C:lesson('Center','Middle of the offensive line, beginning the play with the snap.',['Deliver a clean snap and establish legal blocking position.','Communicate front identifiers and line calls used by the team.','Stay balanced through the block and avoid reaching.'],['Snap consistency','Stance','First step','Communication'],'A clean snap and balanced first step are the foundation of every rep.')
  });
  addLibrary('football',[
    drill('fb-stance-start','Stance & First Two Steps',10,'Fundamentals','Repeatable stance, reaction to cadence and balanced acceleration.','Cones',['Build a comfortable legal stance for each position group.','React to cadence without guessing.','Take two controlled assignment-specific steps, freeze and check balance.']),
    drill('fb-ball-security','Five-Point Ball Security Circuit',10,'Offense','Secure possession while changing direction and traffic.','Footballs, cones',['Teach the team ball-security points used by the program.','Carry through a cone course at controlled speed.','Add coach pressure with pads only if age, equipment and program policy allow.']),
    drill('fb-route-landmarks','Route Landmark Walkthrough',12,'Offense','Correct splits, route depth and spacing without contact.','Cones, footballs',['Mark route landmarks with cones.','Receivers walk then jog routes at exact depth.','Add quarterback timing after spacing is consistent.']),
    drill('fb-fit-walkthrough','Run-Fit Walkthrough',12,'Defense','Gap responsibility, leverage and pursuit paths without collision.','Cones',['Align the defense to a simple offensive look.','Coach points the run direction and defenders fit assigned lanes at half speed.','Freeze to inspect spacing, then finish with controlled pursuit angles.']),
    drill('fb-flag-tracking','Leverage & Flag/Pursuit Tracking',12,'Defense','Safe angle tracking and keeping leverage.','Cones, flags if applicable',['Ball carrier moves through a channel at controlled speed.','Defender maintains inside/outside leverage assigned by the coach.','Finish with a flag pull or two-hand tag; contact tackling belongs only in qualified programs.']),
    drill('fb-coverage-zones','Coverage Landmark Drops',12,'Defense','Zone spacing, eyes and communication.','Cones, footballs',['Mark landmarks for the called coverage.','Defenders drop at controlled speed while communicating routes.','Add receivers crossing zones and finish with a ball-tracking rep.']),
    drill('fb-special-lanes','Special Teams Lane Discipline',12,'Special Teams','Alignment, lane spacing and return communication.','Cones, football',['Walk through coverage or return lanes without contact.','Add a returner moving through the pattern at half speed.','Reward spacing and communication rather than collisions.']),
    drill('fb-situation-cards','Down/Distance Situation Cards',12,'Team','Assignment recognition based on down, distance and field situation.','Situation cards or coach calls',['Coach announces down, distance and field position.','Players state personnel/unit priority and alignment.','Run the rep at walkthrough or controlled tempo, then review assignment accuracy.'])
  ],{stance:['fb-stance-start'],ball:['fb-ball-security','fb-route-landmarks'],blocking:['fb-stance-start','fb-fit-walkthrough'],tackling:['fb-flag-tracking','fb-fit-walkthrough'],routes:['fb-route-landmarks','fb-coverage-zones'],awareness:['fb-situation-cards','fb-special-lanes']});

  const volleyballGuides={
    rotation:{where:p=>`${p.name} rotates through front- and back-row court zones according to the lineup and selected rules.`,responsibilities:p=>['Know the current rotation and legal starting position.','Transition quickly from serve/receive into the assigned offensive or defensive role.','Communicate seams, free balls and coverage responsibilities.'],skills:p=>['Rotation awareness','Ready posture','Ball control','Communication'],tip:p=>'Know where you start, where you go after contact, and who owns the seam beside you.'},
    default:{where:p=>`${p.name} fills a rotation role on the volleyball court.`,responsibilities:p=>['Be in legal rotation.','Communicate and pursue the next ball.'],skills:p=>['Ball control','Awareness'],tip:p=>'Call the ball early.'}
  };
  fillLessons('volleyball',volleyballGuides,{
    S:lesson('Setter','Moves to the setting target after serve receive or defense and connects the first contact to the attack.',['Get to target quickly while staying available for imperfect passes.','Deliver hittable sets with consistent location.','Communicate tempo and hitter options before and during the rally.'],['Hand position','Footwork to target','Set location','Decision making'],'Beat the ball to the target and square your body before trying to be deceptive.'),
    OH1:lesson('Outside Hitter 1','Rotates through left-front and back-row responsibilities, often handling both serve receive and attacking.',['Pass assigned serve-receive seams.','Transition off the net and approach with controlled timing.','Block or defend according to the rotation and team system.'],['Serve receive','Approach timing','Attacking','Blocking/defense'],'Pass first, then transition—do not let the next job make you rush the first contact.'),
    OH2:lesson('Outside Hitter 2','Rotates through left-side attacking and back-row responsibilities opposite the other outside hitter.',['Pass assigned serve-receive seams.','Create a consistent left-side approach window.','Transition into defense and coverage after the attack.'],['Serve receive','Approach timing','Attacking','Coverage'],'Use the same approach rhythm so the setter can locate you consistently.'),
    MB1:lesson('Middle Blocker 1','Works mainly through middle-front blocking and quick-attack responsibilities while rotating through the court.',['Read the setter and move laterally to close blocks.','Transition off the net for quick attack options.','Call blocking matchups and protect tips when off the net.'],['Block footwork','Reading setters','Quick approach','Transition'],'Move your feet before your hands—arrive balanced so you can press over the net safely.'),
    MB2:lesson('Middle Blocker 2','Shares middle blocking and quick-attack duties across alternate rotations.',['Close blocks with pin defenders.','Create quick-attack availability after transition.','Communicate net matchups and coverage.'],['Block timing','Lateral footwork','Quick attack','Communication'],'Start with a strong read posture and avoid guessing before the setter contacts the ball.'),
    OP:lesson('Opposite','Plays opposite the setter in the rotation, contributing right-side attack, blocking and back-row defense.',['Provide a right-side attacking option.','Block the opponent outside attacker when matched there.','Support setting or defense when the setter takes first contact.'],['Right-side approach','Blocking','Emergency setting','Defense'],'Stay available as a release option even when the pass is off the net.')
  });
  addLibrary('volleyball',[
    drill('vb-serve-zones','Serve to Zones',12,'Serving','Repeatable serving routine and directional control.','Volleyballs, zone targets',['Mark large target zones instead of tiny spots.','Players use the same pre-serve routine every rep.','Track in-bounds accuracy before adding pace.']),
    drill('vb-platform-angles','Platform Angle Passing',12,'Passing','Controlling serve-receive angle with quiet platform movement.','Volleyballs',['Toss or serve from a consistent location.','Passer establishes platform early and directs to target.','Vary left/right only after target control improves.']),
    drill('vb-setter-target','Setter Target Footwork',12,'Setting','Arriving balanced and delivering consistent hittable sets.','Volleyballs, target',['Start with passes near target.','Setter moves feet to get under the ball and squares to the antenna.','Progress to off-target passes while keeping set location consistent.']),
    drill('vb-approach-rhythm','Approach Rhythm',10,'Attacking','Consistent approach sequence and jump timing without chasing power.','Cones, volleyballs',['Mark start and plant locations.','Rehearse approach without a ball.','Add controlled tosses and emphasize timing before arm speed.']),
    drill('vb-block-close','Block Close Footwork',10,'Blocking','Lateral movement and closing the seam with a partner.','Net, cones',['Start two blockers a safe distance apart.','Move together to a called antenna and stop balanced.','Add a controlled hitter cue after footwork is synchronized.']),
    drill('vb-freeball-shape','Free-Ball Team Shape',12,'Team','Communication and transition from easy defensive ball into offense.','Volleyballs, net',['Coach sends a controlled free ball.','Team calls seams, passes to target and transitions to attack.','Freeze occasionally to check spacing and coverage.']),
    drill('vb-rotation-walk','Rotation Walkthrough',12,'Awareness','Legal starting spots and post-serve transitions.','Court, rotation cards',['Place six players in one rotation.','Identify overlap relationships and legal starting positions.','Serve a dead ball, then move immediately into base responsibilities; rotate and repeat.']),
    drill('vb-wash-3ball','Three-Ball Wash',15,'Game','Resetting quickly across serve receive, free ball and transition.','Volleyballs, net',['Coach initiates three different controlled balls in sequence.','Team must communicate and reset between each ball.','Award the point for completing the sequence with organized play, not only kills.'])
  ],{serving:['vb-serve-zones'],passing:['vb-platform-angles','vb-freeball-shape'],setting:['vb-setter-target','vb-freeball-shape'],attacking:['vb-approach-rhythm','vb-wash-3ball'],blocking:['vb-block-close'],awareness:['vb-rotation-walk','vb-freeball-shape']});

  return registry;
});
