'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const sports=require('../sports.js');
const sql=fs.readFileSync(path.resolve(__dirname,'..','schema.sql'),'utf8');
const tables=[...sql.matchAll(/create table(?: if not exists)?\s+([a-z_]+)/gi)].map(m=>m[1]);
assert.equal(new Set(tables).size,tables.length,'duplicate CREATE TABLE name');
const tableSet=new Set(tables);
for(const ref of [...sql.matchAll(/references\s+([a-z_]+)/gi)].map(m=>m[1]))assert.ok(tableSet.has(ref),`reference points to missing table ${ref}`);
for(const required of ['sports','sport_positions','sport_layouts','competition_profiles','leagues','team_staff_contacts','team_documents','lineups','lineup_periods','position_assignments','lineup_sequences','lineup_presets','game_sessions','game_period_scores','game_checkins','game_substitutions','practice_plans','skills','lessons'])assert.ok(tableSet.has(required),`missing shared multi-sport table ${required}`);
for(const legacy of ['batting_orders','defensive_presets','game_pitch_counts','pitching_appearances'])assert.ok(!tableSet.has(legacy),`legacy baseball-specific core table remains: ${legacy}`);
assert.ok(tableSet.has('baseball_game_pitch_counts'),'baseball pitch extension missing');
assert.ok(tableSet.has('baseball_pitching_appearances'),'baseball pitching extension missing');
assert.ok(!/half\s+text\s+check/i.test(sql),'game session side label must not be hard-coded to Top/Bottom');
assert.ok(!/batting_index/i.test(sql),'game session sequence cursor must be generic');
assert.match(sql,/current_unit_key text/,'football/multi-unit support missing');
assert.match(sql,/unit_key text not null default 'default'/,'sport positions must be unit-scoped');
assert.match(sql,/primary key\(sport_id, unit_key, code\)/,'sport position/layout key must include unit');
assert.match(sql,/layout_key text not null default 'standard'/,'lineup periods/presets must retain selected layout');
assert.match(sql,/slot_key text not null/,'position assignments/substitutions must use unique layout slots');
assert.match(sql,/role_code text not null/,'slot assignments must retain roster/development role');
assert.match(sql,/sport_attributes jsonb/,'roster sport-specific attributes must be extensible');
assert.match(sql,/default_layouts jsonb/,'teams must persist unit-specific default layouts');
assert.match(sql,/branding jsonb/,'teams must persist branding');
assert.match(sql,/home_location jsonb/,'teams must persist home location');
assert.match(sql,/local_rules_note text/,'teams must persist local rule overrides');
assert.match(sql,/local_rule_details jsonb/,'teams must persist structured local rule details');
assert.match(sql,/storage_key text not null unique/,'team documents require object-storage key');
const generated=(sql.split('-- BEGIN GENERATED SPORT REGISTRY')[1]||'').split('-- END GENERATED SPORT REGISTRY')[0]||'';
for(const sport of Object.values(sports)){
  assert.ok(generated.includes(`values ('${sport.key}','${sport.name}'`),`generated schema missing sport ${sport.key}`);
  assert.ok(generated.includes(`\"scoreModel\":\"${sport.scoreModel}\"`),`${sport.key}: generated score model drifted`);
  assert.ok(generated.includes('\"scoreActions\"'),`${sport.key}: generated score actions missing`);
  assert.ok(generated.includes(`\"adapterVersion\":${sport.adapterVersion}`),`${sport.key}: generated adapter version drifted`);
  const posRows=(generated.match(new RegExp(`insert into sport_positions[^\n]+from sports where code='${sport.key}'`,'g'))||[]).length;
  const layoutRows=(generated.match(new RegExp(`insert into sport_layouts[^\n]+from sports where code='${sport.key}'`,'g'))||[]).length;
  assert.equal(posRows,sport.allPositions.length,`${sport.key}: schema unit-position seed count drifted`);
  assert.equal(layoutRows,sport.units.reduce((n,u)=>n+u.layouts.length,0),`${sport.key}: schema layout seed count drifted`);
}
console.log(`PASS schema contract: ${tables.length} tables, ${Object.keys(sports).length} sport seeds synchronized`);
