'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const root=path.resolve(__dirname,'..');
const app=fs.readFileSync(path.join(root,'app.js'),'utf8');
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
const sw=fs.readFileSync(path.join(root,'sw.js'),'utf8');
const manifest=JSON.parse(fs.readFileSync(path.join(root,'manifest.webmanifest'),'utf8'));
assert.ok(html.indexOf('./sports.js')<html.indexOf('./competition-profiles.js'),'sports registry must load before competition profiles');
assert.ok(html.indexOf('./competition-profiles.js')<html.indexOf('./core/sport-runtime.js'),'competition profiles must load before shared runtime/app');
assert.ok(html.indexOf('./core/file-store.js')<html.indexOf('./app.js'),'file store must load before app');
assert.ok(html.indexOf('./core/sport-runtime.js')<html.indexOf('./app.js'),'shared runtime must load before app');
assert.ok(sw.includes("'./sports.js'"),'service worker must cache sports registry');
assert.ok(sw.includes("'./competition-profiles.js'"),'service worker must cache competition profile registry');
assert.ok(sw.includes("'./core/file-store.js'"),'service worker must cache file store');
assert.ok(sw.includes("'./core/sport-runtime.js'"),'service worker must cache shared sport runtime');
assert.ok(app.includes("const SPORTS = window.TEAM_APP_SPORTS"),'app must consume sport registry');
assert.ok(app.includes('window.TEAM_APP_CORE'),'app must consume shared sport runtime');
assert.ok(app.includes('unitLayoutKeys'),'per-unit/per-period layout state missing');
assert.ok(app.includes('function applyTeamLayout(layoutKey)'),'shared layout application missing');
assert.ok(app.includes('function renderSurfaceDecorations()'),'shared surface renderer missing');
assert.ok(app.includes("sportCapability('pitchTracking')"),'sport-special capability gating missing');
assert.ok(app.includes("sportCapability('sequenceOrder')"),'ordered-lineup gating missing');
assert.ok(!app.includes('const POSITIONS ='),'legacy hard-coded position constant returned');
assert.ok(!app.includes('POSITION_NAMES ='),'legacy hard-coded position names returned');
assert.ok(!app.includes('pos-${pos.toLowerCase()}'),'position placement must not depend on baseball CSS classes');
assert.match(manifest.name,/Coach/,'PWA manifest should describe coach product');
assert.ok(/team-app-live-v1\.9\.0/.test(sw),'cache version not bumped');
assert.ok(html.indexOf('./core/e2ee.js')<html.indexOf('./cloud-client.js'),'E2EE runtime must load before cloud client');
assert.ok(html.indexOf('./cloud-client.js')<html.indexOf('./app.js'),'cloud client must load before app');
assert.ok(app.includes('function renderCoachCenter()'),'coach center missing');
assert.ok(app.includes('function renderTeamSetupModal()'),'team setup workflow missing');
assert.ok(app.includes('function saveDocumentFromForm'),'team document workflow missing');
console.log('PASS static architecture contract');
