import express from 'express';
import crypto from 'node:crypto';
import {z} from 'zod';
import {query,tx} from './db.js';
import {requireIdentity,requireTeamRole,COACH_ROLES,membershipFor} from './access.js';
import {seal} from './crypto-seal.js';
import {notifyUsers} from './notifications.js';

const router=express.Router();router.use(requireIdentity);
const fieldSchema=z.object({id:z.string().min(1).max(80),label:z.string().min(1).max(180),type:z.enum(['text','textarea','number','date','yes_no','select','checkbox']),required:z.boolean().default(false),options:z.array(z.string().max(120)).max(50).optional()});
const templateSchema=z.object({title:z.string().min(1).max(180),description:z.string().max(4000).optional(),visibility:z.enum(['coaches','team','guardians','private']).default('guardians'),requiresSignature:z.boolean().default(false),fields:z.array(fieldSchema).max(50)});

router.post('/teams/:teamId/forms',requireTeamRole(COACH_ROLES),async(req,res,next)=>{try{const b=templateSchema.parse(req.body);const {rows}=await query(`insert into form_templates(team_id,title,description,visibility,schema,requires_signature,created_by) values($1,$2,$3,$4,$5::jsonb,$6,$7) returning id,title,description,visibility,schema,requires_signature,created_at`,[req.params.teamId,b.title,b.description||null,b.visibility,JSON.stringify({fields:b.fields}),b.requiresSignature,req.teamApp.user.id]);res.status(201).json(rows[0]);}catch(e){next(e);}});

router.get('/teams/:teamId/forms',requireTeamRole(null),async(req,res,next)=>{try{const coach=COACH_ROLES.includes(req.teamMembership.role);const {rows}=await query(`select ft.id,ft.title,ft.description,ft.visibility,ft.schema,ft.requires_signature,ft.created_at,
  coalesce((select jsonb_agg(jsonb_build_object('id',fa.id,'athlete_id',fa.athlete_id,'athlete_name',case when ap.id is not null then trim(ap.first_name||' '||ap.last_name) end,'due_at',fa.due_at,'submitted',exists(select 1 from form_submissions fs where fs.assignment_id=fa.id and fs.submitted_by=$2)) order by fa.created_at) from form_assignments fa left join athlete_profiles ap on ap.id=fa.athlete_id where fa.form_template_id=ft.id and fa.assigned_user_id=$2),'[]'::jsonb) as my_assignments
  from form_templates ft where ft.team_id=$1 and ft.archived_at is null ${coach?'':"and ft.visibility in ('team','guardians') and exists(select 1 from form_assignments mine where mine.form_template_id=ft.id and mine.assigned_user_id=$2)"} order by ft.created_at desc`,[req.params.teamId,req.teamApp.user.id]);res.json(rows);}catch(e){next(e);}});

router.post('/teams/:teamId/forms/:formId/assign',requireTeamRole(COACH_ROLES),async(req,res,next)=>{try{const b=z.object({athleteId:z.string().uuid().optional(),athleteClientKey:z.string().max(180).optional(),userId:z.string().uuid(),dueAt:z.string().datetime().optional()}).parse(req.body);let athleteId=b.athleteId||null;if(!athleteId&&b.athleteClientKey){athleteId=(await query(`select ap.id from roster_memberships rm join athlete_profiles ap on ap.id=rm.athlete_id where rm.team_id=$1 and ap.client_key=$2 limit 1`,[req.params.teamId,b.athleteClientKey])).rows[0]?.id||null;if(!athleteId)return res.status(400).json({error:'athlete_not_on_team'});}const member=(await query('select role from team_memberships where team_id=$1 and user_id=$2',[req.params.teamId,b.userId])).rows[0];if(!member)return res.status(400).json({error:'assigned_user_not_on_team'});const targetForm=(await query('select visibility from form_templates where id=$1 and team_id=$2 and archived_at is null',[req.params.formId,req.params.teamId])).rows[0];if(!targetForm)return res.status(404).json({error:'form_not_found'});if(['coaches','private'].includes(targetForm.visibility)&&!COACH_ROLES.includes(member.role))return res.status(400).json({error:'restricted_form_requires_coach_assignee'});if(athleteId){const linked=(await query('select 1 from guardian_relationships where athlete_id=$1 and guardian_user_id=$2',[athleteId,b.userId])).rowCount;if(!linked)return res.status(400).json({error:'athlete_not_linked_to_assigned_user'});}const existing=(await query(`select fa.* from form_assignments fa join form_templates ft on ft.id=fa.form_template_id where ft.id=$1 and ft.team_id=$2 and fa.assigned_user_id=$3 and fa.athlete_id is not distinct from $4::uuid order by fa.created_at desc limit 1`,[req.params.formId,req.params.teamId,b.userId,athleteId])).rows[0];if(existing)return res.status(200).json(existing);let {rows}=await query(`insert into form_assignments(form_template_id,athlete_id,assigned_user_id,due_at,created_by) select id,$3,$4,$5,$6 from form_templates where id=$1 and team_id=$2 on conflict do nothing returning *`,[req.params.formId,req.params.teamId,athleteId,b.userId,b.dueAt||null,req.teamApp.user.id]);if(!rows[0]){rows=(await query(`select fa.* from form_assignments fa join form_templates ft on ft.id=fa.form_template_id where ft.id=$1 and ft.team_id=$2 and fa.assigned_user_id=$3 and fa.athlete_id is not distinct from $4::uuid order by fa.created_at desc limit 1`,[req.params.formId,req.params.teamId,b.userId,athleteId])).rows;}if(!rows[0])return res.status(404).json({error:'form_not_found'});const f=(await query('select title from form_templates where id=$1',[req.params.formId])).rows[0];notifyUsers([b.userId],req.params.teamId,'forms',{title:'Team form assigned',body:`${f?.title||'A team form'} is ready for you.`,payload:{formId:req.params.formId}},).catch(()=>{});res.status(201).json(rows[0]);}catch(e){next(e);}});

router.get('/teams/:teamId/forms/:formId/assignments',requireTeamRole(COACH_ROLES),async(req,res,next)=>{try{
  const {rows}=await query(`select fa.id,fa.athlete_id,fa.assigned_user_id,fa.due_at,fa.created_at,u.display_name as assigned_user_name,u.email as assigned_user_email,
    trim(coalesce(a.first_name,'')||' '||coalesce(a.last_name,'')) as athlete_name,
    exists(select 1 from form_submissions fs where fs.assignment_id=fa.id) as submitted
    from form_assignments fa left join users u on u.id=fa.assigned_user_id left join athlete_profiles a on a.id=fa.athlete_id
    join form_templates ft on ft.id=fa.form_template_id where ft.team_id=$1 and ft.id=$2 order by fa.created_at desc`,[req.params.teamId,req.params.formId]);res.json(rows);
}catch(e){next(e);}});

router.post('/teams/:teamId/forms/:formId/submit',requireTeamRole(null),async(req,res,next)=>{try{
  const b=z.object({assignmentId:z.string().uuid().optional(),athleteId:z.string().uuid().optional(),answers:z.record(z.string(),z.any()),signature:z.object({type:z.enum(['typed','drawn']),name:z.string().min(1).max(160),payload:z.string().max(250000).optional(),consentText:z.string().min(1).max(3000)}).optional()}).parse(req.body);
  const form=(await query('select * from form_templates where id=$1 and team_id=$2 and archived_at is null',[req.params.formId,req.params.teamId])).rows[0];if(!form)return res.status(404).json({error:'form_not_found'});const isCoach=COACH_ROLES.includes(req.teamMembership.role);if(['coaches','private'].includes(form.visibility)&&!isCoach)return res.status(403).json({error:'form_not_visible'});if(form.requires_signature&&!b.signature)return res.status(400).json({error:'signature_required'});
  let assignment=null;if(b.assignmentId){assignment=(await query(`select fa.* from form_assignments fa join form_templates ft on ft.id=fa.form_template_id where fa.id=$1 and ft.id=$2 and ft.team_id=$3`,[b.assignmentId,form.id,req.params.teamId])).rows[0];if(!assignment)return res.status(404).json({error:'assignment_not_found'});if(!isCoach&&assignment.assigned_user_id&&assignment.assigned_user_id!==req.teamApp.user.id)return res.status(403).json({error:'assignment_not_yours'});}else if(!isCoach){const mine=(await query(`select fa.* from form_assignments fa where fa.form_template_id=$1 and fa.assigned_user_id=$2 order by fa.created_at`,[form.id,req.teamApp.user.id])).rows;if(mine.length===0)return res.status(403).json({error:'form_not_assigned_to_user'});if(mine.length>1)return res.status(409).json({error:'assignment_selection_required'});assignment=mine[0];}
  if(Buffer.byteLength(JSON.stringify(b.answers),'utf8')>131072)return res.status(400).json({error:'answers_too_large'});
  const requestedAthleteId=b.athleteId||assignment?.athlete_id||null;if(!isCoach&&requestedAthleteId){const rel=(await query(`select 1 from guardian_relationships gr join roster_memberships rm on rm.athlete_id=gr.athlete_id where gr.athlete_id=$1 and gr.guardian_user_id=$2 and rm.team_id=$3 and gr.may_complete_forms=true`,[requestedAthleteId,req.teamApp.user.id,req.params.teamId])).rows[0];if(!rel)return res.status(403).json({error:'athlete_form_access_denied'});}if(assignment?.athlete_id&&requestedAthleteId&&String(assignment.athlete_id)!==String(requestedAthleteId)&&!isCoach)return res.status(403).json({error:'assignment_athlete_mismatch'});
  const fields=Array.isArray(form.schema?.fields)?form.schema.fields:[];const known=new Set(fields.map(f=>f.id));for(const key of Object.keys(b.answers)){if(!known.has(key))return res.status(400).json({error:'unknown_field',fieldId:key});}for(const field of fields){const value=b.answers[field.id];if(field.required&&((field.type==='checkbox'&&value!==true)||(field.type!=='checkbox'&&(value===undefined||value===null||value===''))))return res.status(400).json({error:'required_field_missing',fieldId:field.id});if(value===undefined||value===null||value==='')continue;if(field.type==='file')return res.status(400).json({error:'file_field_not_enabled',fieldId:field.id});if(['text','textarea','date','yes_no','select'].includes(field.type)&&typeof value!=='string')return res.status(400).json({error:'invalid_field_value',fieldId:field.id});if(typeof value==='string'&&value.length>4000)return res.status(400).json({error:'field_value_too_long',fieldId:field.id});if(field.type==='number'&&!Number.isFinite(Number(value)))return res.status(400).json({error:'invalid_field_value',fieldId:field.id});if(field.type==='checkbox'&&typeof value!=='boolean')return res.status(400).json({error:'invalid_field_value',fieldId:field.id});if(field.type==='yes_no'&&!['Yes','No'].includes(value))return res.status(400).json({error:'invalid_field_value',fieldId:field.id});if(field.type==='select'&&Array.isArray(field.options)&&!field.options.includes(value))return res.status(400).json({error:'invalid_field_value',fieldId:field.id});}
  const ip=String(req.ip||''),ipHash=ip?crypto.createHash('sha256').update(ip).digest('hex'):null;
  const result=await tx(async c=>{
    const sub=(await c.query(`insert into form_submissions(form_template_id,assignment_id,athlete_id,submitted_by,answers) values($1,$2,$3,$4,$5::jsonb)
      on conflict(form_template_id,assignment_id,submitted_by) do update set athlete_id=excluded.athlete_id,answers=excluded.answers,updated_at=now(),submitted_at=now() returning *`,[form.id,assignment?.id||b.assignmentId||null,requestedAthleteId,req.teamApp.user.id,JSON.stringify(b.answers)])).rows[0];
    if(b.signature){const encrypted=b.signature.payload?seal(b.signature.payload,`form-signature:${sub.id}`):null;await c.query(`insert into form_signatures(submission_id,signer_user_id,signer_name,consent_text,signature_type,signature_payload_encrypted,ip_hash,user_agent) values($1,$2,$3,$4,$5,$6,$7,$8)
      on conflict(submission_id) do update set signer_user_id=excluded.signer_user_id,signer_name=excluded.signer_name,consent_text=excluded.consent_text,signature_type=excluded.signature_type,signature_payload_encrypted=excluded.signature_payload_encrypted,signed_at=now(),ip_hash=excluded.ip_hash,user_agent=excluded.user_agent`,[sub.id,req.teamApp.user.id,b.signature.name,b.signature.consentText,b.signature.type,encrypted,ipHash,req.get('user-agent')||null]);}
    return sub;
  });res.status(201).json({submissionId:result.id,submittedAt:result.submitted_at});
}catch(e){next(e);}});

router.get('/teams/:teamId/forms/:formId/submissions',requireTeamRole(COACH_ROLES),async(req,res,next)=>{try{const {rows}=await query(`select s.id,s.athlete_id,s.submitted_by,s.answers,s.submitted_at,s.updated_at,u.display_name as submitted_by_name,fs.signed_at,fs.signer_name from form_submissions s join form_templates f on f.id=s.form_template_id left join users u on u.id=s.submitted_by left join form_signatures fs on fs.submission_id=s.id where f.team_id=$1 and f.id=$2 order by s.submitted_at desc`,[req.params.teamId,req.params.formId]);res.json(rows);}catch(e){next(e);}});

export default router;
